
"use client";

import React from 'react';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
} from "@/components/ui/dialog";
import { Skeleton } from '../ui/skeleton';

interface InsightModalProps {
  isOpen: boolean;
  onClose: () => void;
  title: string;
  insight: string;
  loading: boolean;
}

export default function InsightModal({ isOpen, onClose, title, insight, loading }: InsightModalProps) {
  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>AI Insight for: {title}</DialogTitle>
          <DialogDescription>
            This analysis was generated by Gemini.
          </DialogDescription>
        </DialogHeader>
        <div className="py-4">
          {loading ? (
            <div className="space-y-2">
                <Skeleton className="h-4 w-full" />
                <Skeleton className="h-4 w-full" />
                <Skeleton className="h-4 w-3/4" />
            </div>
          ) : (
            <p className="text-sm text-foreground">{insight}</p>
          )}
        </div>
      </DialogContent>
    </Dialog>
  );
}
